---

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

driver:
  name: vagrant

suites:
  - name: hab_elasticsearch
    run_list:
      - recipe[hab_elasticsearch::default]
      - recipe[hab_elasticsearch::kibana]
    verifier:
      inspec_tests:
        - test/smoke/default

